# Generated by Django 4.2.4 on 2023-08-02 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_remove_note_id_note_tid'), ('main', '0003_note_monospace')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('link_share', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tid', models.CharField(default=main.models.ran10, max_length=10, primary_key=True, serialize=False)),
                ('monospace', models.BooleanField(default=False)),
            ],
        ),
    ]
