# Generated by Django 4.0.4 on 2022-05-12 12:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AddField(
            model_name='note',
            name='tid',
            field=models.CharField(default=main.models.ran10, max_length=10, primary_key=True, serialize=False),
        ),
    ]
